name: Bump casks on schedule or request

on:
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  # schedule:
  #   # Every 3 hours 23 minutes past the hour
  #   - cron: "23 */3 * * *"

permissions:
  contents: read

jobs:
  auto-bump:
    if: github.repository == 'Homebrew/homebrew-cask'
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: true
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Get list of auto-bump casks
        id: autobump
        run: echo "autobump_list=$(xargs < "$(brew --repo homebrew/cask)"/.github/autobump.txt)" >> "$GITHUB_OUTPUT"

      - name: Bump casks
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CASK_REPO_WORKFLOW_TOKEN }}
          casks: ${{ github.event.inputs.casks || steps.autobump.outputs.autobump_list }}
        env:
          HOMEBREW_TEST_BOT_AUTOBUMP: 1

      # - name: Commit and push if changed
      #   run: |-
      #     git diff
      #     git config --global user.email "${{ vars.USER_EMAIL }}"
      #     git config --global user.name "${{ vars.USER_NAME }}"
      #     git add -A
      #     git commit -m "chore: update blog posts" || exit 0
      #     git push
